server:
  port: 7001
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端藏是注册中我的职员威是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-ur1:
      #没与EurekaServer交互的地址登询服务和注册服务都需要依赖这个地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/