server:
  port: 8001
spring:
  application:
    name: cloud-payment-hystrix-service
eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7002/eureka/ #集群版
      defaultZone: http://eureka7001.com:7001/eureka/ #单机版